name: Bug report
description: Something broken in the module
labels: ['bug']
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Module version
      description: Output of `(Get-Module {{ModuleName}} -ListAvailable).Version`
    validations:
      required: true
  - type: input
    id: ps-version
    attributes:
      label: PowerShell version
      description: Output of `$PSVersionTable.PSVersion`
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
    validations:
      required: true
